services:
  api:
    build:
      context: ..
      dockerfile: src/pgs_api/Dockerfile
    container_name: pgs_api
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=photography_server
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - ENVIRONMENT=development
    ports:
      - "8000:8000"
    volumes:
      - ../photos:/app/photos
    depends_on:
      postgres:
        condition: service_healthy
    command: [ "uv", "run", "run.py" ]
    working_dir: /app/src/pgs_api
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/healthcheck" ]
      interval: 60s
      timeout: 10s
      retries: 5
    develop:
      watch:
        - action: sync
          path: ../src/pgs_api/src
          target: /app/src/pgs_api/src
        - action: sync
          path: ../src/pgs_db/src
          target: /app/src/pgs_db/src
        - action: rebuild
          path: ../src/pgs_api/pyproject.toml
