services:
  frontend:
    build:
      context: ../src/pgs_frontend
      dockerfile: Dockerfile
    container_name: pgs_frontend
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
    depends_on:
      - api
    command: [ "npm", "run", "dev" ]
    develop:
      watch:
        - action: sync
          path: ../src/pgs_frontend/src
          target: /app/src
        - action: sync
          path: ../src/pgs_frontend/public
          target: /app/public
        - action: sync
          path: ../src/pgs_frontend/tailwind.config.ts
          target: /app/tailwind.config.ts
        - action: sync
          path: ../src/pgs_frontend/tsconfig.json
          target: /app/tsconfig.json
        - action: sync
          path: ../src/pgs_frontend/postcss.config.mjs
          target: /app/postcss.config.mjs
        - action: rebuild
          path: ../src/pgs_frontend/package.json
        - action: rebuild
          path: ../src/pgs_frontend/package-lock.json
        - action: rebuild
          path: ../src/pgs_frontend/next.config.ts
