.PHONY: dev build start lint format install clean

dev:
	npm run dev

build:
	npm run build

start:
	npm run start

lint:
	npm run lint

format:
	npx prettier --write .

install:
	npm install

clean:
	rm -rf .next node_modules
